# Classes
class ULID
  VERSION: String
  ENCODING_CHARS: Array[String]
  TIME_PART_LENGTH: 10
  RANDOMNESS_PART_LENGTH: 16
  ENCODED_ID_LENGTH: 26
  TIME_OCTETS_LENGTH: 6
  RANDOMNESS_OCTETS_LENGTH: 10
  OCTETS_LENGTH: 16
  MAX_MILLISECONDS: 281474976710655
  MAX_ENTROPY: 1208925819614629174706175
  TIME_FORMAT_IN_INSPECT: '%Y-%m-%d %H:%M:%S.%3N %Z'
  MONOTONIC_GENERATOR: MonotonicGenerator
  include Comparable

  class Error < StandardError
  end

  class OverflowError < Error
  end

  class ParserError < Error
  end

  class MonotonicGenerator
    attr_accessor latest_milliseconds: Integer?
    attr_accessor latest_entropy: Integer?
    def initialize: -> void
    def generate: -> ULID
    def reset: -> void
    def freeze: -> void
  end

  type octets = [Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer]
  type time_octets = [Integer, Integer, Integer, Integer, Integer, Integer]
  type randomness_octets = [Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer]

  @string: String
  @integer: Integer
  @octets: octets
  @time_octets: time_octets
  @randomness_octets: randomness_octets
  @inspect: String
  @time: Time
  @next: ULID

  def self.generate: (?moment: Time | Integer, ?entropy: Integer) -> ULID
  def self.monotonic_generate: -> ULID
  def self.current_milliseconds: -> Integer
  def self.time_to_milliseconds: (Time time) -> Integer
  def self.reasonable_entropy: -> Integer
  def self.parse: (String string) -> ULID
  def self.valid?: (untyped string) -> bool
  attr_reader milliseconds: Integer
  attr_reader entropy: Integer
  def initialize: (milliseconds: Integer, entropy: Integer) -> void
  def to_str: -> String
  alias to_s to_str
  def to_i: -> Integer
  alias hash to_i
  def <=>: (ULID other) -> Integer
         | (untyped other) -> Integer?
  def inspect: -> String
  def eql?: (untyped other) -> bool
  alias == eql?
  def ===: (untyped other) -> bool
  def to_time: -> Time
  def octets: -> octets
  def time_octets: -> time_octets
  def randomness_octets: -> randomness_octets
  def next: -> ULID
  alias succ next
  def freeze: -> self

  private
  def octets_from_integer: (Integer integer, length: Integer) -> Array[Integer]
  def inverse_of_digits: (Array[Integer] reversed_digits) -> Integer
end
