# https://docs.github.com/ja/actions/reference/workflow-syntax-for-github-actions
name: CI
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/ci.yml'
      - 'lib/**'
      - 'test/**'
      - 'spec/**'
      - '.rspec'
      - '**.gemspec'
      - 'Gemfile'
      - 'Rakefile'
      - '.ruby-version'
  pull_request:
    paths:
      - '.github/workflows/ci.yml'
      - 'lib/**'
      - 'test/**'
      - 'spec/**'
      - '.rspec'
      - '**.gemspec'
      - 'Gemfile'
      - 'Rakefile'
      - '.ruby-version'

jobs:
  test:
    timeout-minutes: 15
    strategy:
      fail-fast: false
      # Syntax https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs
      matrix:
        # macos is covered in nix ci
        os: ['ubuntu-24.04']
        # Due to https://github.com/actions/runner/issues/849, we have to use quotes for 'n.0'
        ruby: ['head', '3.3', '3.2']
    runs-on: ${{ matrix.os }}
    steps:
      # libyaml is needed for psych, see https://github.com/actions/runner-images/issues/9895
      # GitHub installs libyaml-dev in latest runners, but often dropped in new runners.
      # So, make sure to check here even if using runner installed.
      - name: Install libyaml
        if: startsWith(matrix.os, 'ubuntu-')
        run: sudo apt-get install --no-install-recommends --assume-yes libyaml-dev
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        env:
          # https://github.com/kachick/ruby-ulid/blob/104834846baf5caa1e8536a11c43acdd56fc849c/CONTRIBUTING.md#adding-dependencies-for-this-gem
          BUNDLE_WITHOUT: development
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - run: bundle exec rake test_all --suppress-backtrace='\/bundle'
        env:
          # Need same specifying for now(want to squash)
          BUNDLE_WITHOUT: development
