# https://docs.github.com/ja/actions/reference/workflow-syntax-for-github-actions
name: CI
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'
    branches:
      - main
    paths:
      - '.github/workflows/ci.yml'
      - 'lib/**'
      - 'test/**'
      - 'spec/**'
      - '.rspec'
      - '**.gemspec'
      - 'Gemfile'
      - 'Rakefile'
      - '.ruby-version'
  pull_request:
    paths:
      - '.github/workflows/ci.yml'
      - 'lib/**'
      - 'test/**'
      - 'spec/**'
      - '.rspec'
      - '**.gemspec'
      - 'Gemfile'
      - 'Rakefile'
      - '.ruby-version'

jobs:
  test:
    timeout-minutes: 15
    strategy:
      fail-fast: false
      # Syntax https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs
      matrix:
        # macos is covered in nix ci
        os: ['ubuntu-24.04']
        # Due to https://github.com/actions/runner/issues/849, we have to use quotes for 'n.0'
        # Avoiding 'head'(ruby-head) in CI. See GH-749 and GH-590
        ruby: ['3.4', '3.3']
    runs-on: ${{ matrix.os }}
    env:
      # https://github.com/kachick/ruby-ulid/blob/104834846baf5caa1e8536a11c43acdd56fc849c/CONTRIBUTING.md#adding-dependencies-for-this-gem
      BUNDLE_WITHOUT: development
    steps:
      - uses: actions/checkout@v5
      - uses: ruby/setup-ruby@829114fc20da43a41d27359103ec7a63020954d4 # v1.255.0
        with:
          ruby-version: ${{ matrix.ruby }}
          # Enabling is the recommended way, but it cannot detect runner changes in early stage.
          # So disable it is better for test job, do not mind in other jobs
          bundler-cache: false # runs 'bundle install' and caches installed gems automatically
      - run: bundle install
      - run: bundle exec rake test_all --suppress-backtrace='\/bundle'
      - run: bundle exec rake validate_gem
