# https://docs.github.com/ja/actions/reference/workflow-syntax-for-github-actions
name: CI
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/ci.yml'
      - 'lib/**'
      - 'test/**'
      - 'spec/**'
      - '.rspec'
      - '**.gemspec'
      - 'Gemfile'
      - 'Rakefile'
  pull_request:
    paths:
      - '.github/workflows/ci.yml'
      - 'lib/**'
      - 'test/**'
      - 'spec/**'
      - '.rspec'
      - '**.gemspec'
      - 'Gemfile'
      - 'Rakefile'
jobs:
  test:
    strategy:
      fail-fast: false
      # Syntax https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs
      matrix:
        os: ['ubuntu-latest']
        # Due to https://github.com/actions/runner/issues/849, we have to use quotes for '3.0'
        ruby: ['head', '3.1', '3.0', '2.7']
        # # Disabled macos runner. This gem should work because of it is written in pure ruby :). And the runner is too slow and often be stacked.
        # include:
        #   - os: 'macos-latest'
        #     ruby: '3.1'
        # # Windows CI takes longtime. It has been succeeded in #223, it is enough for now.
        # - os: 'windows-latest'
        #   ruby: '3.1'
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        env:
          # https://github.com/kachick/ruby-ulid/blob/104834846baf5caa1e8536a11c43acdd56fc849c/CONTRIBUTING.md#adding-dependencies-for-this-gem
          BUNDLE_WITHOUT: development
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - run: bundle exec rake test_all --suppress-backtrace='\/bundle'
        env:
          # Need same specifying for now(want to squash)
          BUNDLE_WITHOUT: development
