name: Deploy documents
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: git setting
        run: |
          git config --local user.email "kachick1@gmail.com"
          git config --local user.name "Kenichi Kamiya"
      - name: Update YARD documents and Deploy to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          DATE=`"%Y%m%d-%H%M-UTC"`
          BRANCH_NAME="documents-$DATE"
          git checkout -b "$BRANCH_NAME"
          bundle exec yard --output-dir docs
          git add docs
          git commit -m 'Update YARD documents ref: #28' docs
          git push origin "$BRANCH_NAME":gh-pages
